### ISSUE TITLE
Unity 5.3 [Coherent UI] (Error) Unsupported Unity3D renderer

### ISSUE THREAD

**Issue by philiptolk** [CoherentLabs/CoherentUIMobileOpenSource#1]

**Comment by philiptolk** [comment]
[Coherent UI](Error) Trying to create Unity3D texture renderer with invalid type = -1. If you have changed the renderer type in Unity, please restart the Editor

**Comment by IvanTheChemist** [comment]
Hi pmtolk,

On Mac OSX there is "Graphics: New OpenGL Core (GL3/4) back-end for Mac OS X editor and player" and it is enabled by default. Our product currently expects OpenGL 2.

The project is open to pull requests for implementations with a working OpenGL newer than 2.
